use SM_769068897;

DELETE FROM [dbo].[T_RCEIVED_CHEQUES];
DELETE FROM [dbo].[T_Receipt_Voucher];
delete from t_issued_cheques;
delete from t_payment_voucher;
delete FROM T_PURCHASE_VOUCHERS;
DELETE T_Invoice;
DELETE [dbo].[T_Account_Transactions];
DELETE T_CUSTOMERS;
DELETE T_SUPPLIERS;
DELETE T_Accounts_Master;
--DELETE T_SETTINGS;
--DELETE [dbo].[T_SM_Sequences]
GO
--BEGIN		-- [T_SM_Sequences]
--	insert into [T_SM_Sequences]
--	(				F_TRANSACTION,		F_DESCRIPTION,		F_PRECODE
--	,F_NEXTNUMBER	,F_LASTSEQUENCE		,F_NEXTSEQUENCE		,F_FORMAT
--	,F_NUMBERLIMIT	,F_USERID)
--	select 
--					[TRANSACTION],			[DESCRIPTION],		PRECODE
--	,NEXTNUMBER		,LASTSEQUENCE		,NEXTSEQUENCE		,[FORMAT]
--	,NUMBERLIMIT	,USERID
--	from OASO.[dbo].[TransactionSequences]
--END;


BEGIN		-- ACCOUNTS MASTER
	--delete foreignkey
	ALTER TABLE [dbo].[T_Accounts_Master] DROP CONSTRAINT [FK_T_Accounts_Master_T_Accounts_Master]
	

	set identity_insert t_accounts_master on;
	insert into T_Accounts_Master
	(F_ID,		F_AccCd,		F_AccNm,		F_ParentAccID)
	select 
	RecordID	,AccountCode,	AccountName,	ParentAccount 
	from OASO.dbo.AccountsMaster;

	--create foreignkey
	SET IDENTITY_INSERT T_ACCOUNTS_MASTER OFF;

	ALTER TABLE [dbo].[T_Accounts_Master] with  nocheck ADD  CONSTRAINT [FK_T_Accounts_Master_T_Accounts_Master] 
	FOREIGN KEY([F_ParentAccID])
	REFERENCES [dbo].[T_Accounts_Master] ([F_ID])
	
END;
GO

BEGIN	-- CUSTOMERS
	-- SETUP THE DISTRIC, AREA, BUSINESS TYPES
	-- [F_ENUM_GRPID]=4;--BUSINESS TYPES
	--[F_ENUM_GRPID]=5;--AREAS
	--[F_ENUM_GRPID]=6;--DISTRICTS

	INSERT INTO T_SM_ENUMS (F_ENUM_GRPID, F_VAL)
	SELECT DISTINCT 4, BUSINESSTYPE 
	FROM OASO.dbo.Customers WHERE BUSINESSTYPE IS NOT NULL
		and (BUSINESSTYPE COLLATE DATABASE_DEFAULT  not in (select F_VAL from T_SM_ENUMS where F_ENUM_GRPID=4));
	INSERT INTO T_SM_ENUMS (F_ENUM_GRPID, F_VAL)
	SELECT DISTINCT 5, Area 
	FROM OASO.dbo.Customers WHERE AREA IS NOT NULL
		and AREA COLLATE DATABASE_DEFAULT  not in  (select F_VAL from T_SM_ENUMS where F_ENUM_GRPID=5);
	INSERT INTO T_SM_ENUMS (F_ENUM_GRPID, F_VAL)
	SELECT DISTINCT 6, District
	FROM OASO.dbo.Customers WHERE DISTRICT IS NOT NULL
		and DISTRICT COLLATE DATABASE_DEFAULT not in (select F_VAL from T_SM_ENUMS where F_ENUM_GRPID=6);

	SET IDENTITY_INSERT T_CUSTOMERS ON;
	INSERT INTO T_Customers 
	(F_Id,			F_AccountID			,F_Adr			,F_Cd		
	,F_email		,F_Mobile			, F_Nm			,F_Tel
	,F_Area				
	,F_BusinessType
	,F_District		
	)
	SELECT 
	C.ID			,C.AccountID		,[Address]		,C.Code		
	,C.email		,C.Mobile			,C.[Name]		,C.Tel	
	,(SELECT F_ID FROM T_SM_ENUMS WHERE F_ENUM_GRPID=5 AND F_VAL COLLATE DATABASE_DEFAULT =C.Area COLLATE DATABASE_DEFAULT  )		
	,(SELECT F_ID FROM T_SM_ENUMS WHERE F_ENUM_GRPID=4 AND F_VAL COLLATE DATABASE_DEFAULT =C.BusinessType COLLATE DATABASE_DEFAULT )
	,(SELECT F_ID FROM T_SM_ENUMS WHERE F_ENUM_GRPID=6 AND F_VAL COLLATE DATABASE_DEFAULT=C.District		COLLATE DATABASE_DEFAULT )
	FROM OASO.dbo.Customers	C;
	SET IDENTITY_INSERT T_CUSTOMERS OFF;
END;
GO

BEGIN	-- SUPPLIERS
	-- SETUP THE DISTRIC, AREA, BUSINESS TYPES
	--[F_ENUM_GRPID]=4;--BUSINESS TYPES
	--[F_ENUM_GRPID]=5;--AREAS
	--[F_ENUM_GRPID]=6;--DISTRICTS

	INSERT INTO T_SM_ENUMS (F_ENUM_GRPID, F_VAL)
	SELECT DISTINCT 4, BUSINESSTYPE 
	FROM OASO.dbo.SUPPLIERS WHERE BUSINESSTYPE IS NOT NULL 
		and BUSINESSTYPE COLLATE DATABASE_DEFAULT  not in (select F_VAL from T_SM_ENUMS where F_ENUM_GRPID=4);

	INSERT INTO T_SM_ENUMS (F_ENUM_GRPID, F_VAL)
	SELECT DISTINCT 5, Area 
	FROM OASO.dbo.SUPPLIERS WHERE AREA IS NOT NULL
		and AREA COLLATE DATABASE_DEFAULT  not in (select F_VAL from T_SM_ENUMS where F_ENUM_GRPID=5);
	INSERT INTO T_SM_ENUMS (F_ENUM_GRPID, F_VAL)
	SELECT DISTINCT 6, District
	FROM OASO.dbo.SUPPLIERS WHERE DISTRICT IS NOT NULL
		and DISTRICT COLLATE DATABASE_DEFAULT  not in (select F_VAL from T_SM_ENUMS where F_ENUM_GRPID=6);

	SET IDENTITY_INSERT T_SUPPLIERS ON;
	INSERT INTO T_SUPPLIERS 
	(F_Id,			F_AccountID			,F_Address			,F_Code		
	,F_email		,F_Mobile			, F_Name			,F_Tel
	,F_Area				
	,F_BusinessType
	,F_District		
	)
	SELECT 
	C.ID			,C.AccountID		,[Address]		,C.Code		
	,C.email		,C.Mobile			,C.[Name]		,C.Tel	
	,(SELECT F_ID FROM T_SM_ENUMS WHERE F_ENUM_GRPID=5 AND F_VAL COLLATE DATABASE_DEFAULT =C.Area COLLATE DATABASE_DEFAULT  )		
	,(SELECT F_ID FROM T_SM_ENUMS WHERE F_ENUM_GRPID=4 AND F_VAL COLLATE DATABASE_DEFAULT =C.BusinessType COLLATE DATABASE_DEFAULT )
	,(SELECT F_ID FROM T_SM_ENUMS WHERE F_ENUM_GRPID=6 AND F_VAL COLLATE DATABASE_DEFAULT=C.District		COLLATE DATABASE_DEFAULT )
	FROM OASO.dbo.SUPPLIERS	C;
	SET IDENTITY_INSERT T_SUPPLIERS OFF;
END;
GO

BEGIN	-- ACCOUNT TRANSACTIONS
	-- SETUP TRANSACTION TYPES
	--DELETE T_SM_ENUMS WHERE [F_ENUM_GRPID]=7;--TRANSACTION TYPES

	INSERT INTO T_SM_ENUMS (F_ENUM_GRPID, F_VAL)
	SELECT DISTINCT 7, TRANSACTIONTYPE 
	FROM OASO.dbo.ACCOUNTTRANSACTIONS WHERE TRANSACTIONTYPE IS NOT NULL
		and TRANSACTIONTYPE COLLATE DATABASE_DEFAULT  not in (select F_VAL from T_SM_ENUMS where F_ENUM_GRPID=7);

	SET IDENTITY_INSERT T_ACCOUNT_TRANSACTIONS ON;
	INSERT INTO T_ACCOUNT_TRANSACTIONS 
	(F_Id			,F_DATE						,F_DESCRIPTION		
	,F_ACCOUNTID	,F_AMOUNT			,F_VOUCHERNO		,F_SETTLEDAMOUNT
	,F_TRANID
	,F_TRANTYPE				
	)
	SELECT 
	T.RECORDID		,T.[DATE]					,T.[DESCRIPTION]
	,T.ACCOUNTID	,T.AMOUNT			,T.VOUCHERNO		,T.SETTLEDAMOUNT
	,T.TRANSACTIONID
	,(SELECT F_ID FROM T_SM_ENUMS WHERE F_ENUM_GRPID=7 AND F_VAL COLLATE DATABASE_DEFAULT =T.TRANSACTIONTYPE COLLATE DATABASE_DEFAULT  )		
	FROM OASO.dbo.ACCOUNTTRANSACTIONS	T;
	SET IDENTITY_INSERT T_ACCOUNT_TRANSACTIONS OFF;
END;
GO
-- do not execute this step. settings table already customize to SM format
--BEGIN	-- SETTINGS
--	SET IDENTITY_INSERT T_SETTINGS ON;
--	INSERT INTO T_SETTINGS 
--	(F_Id			,F_NAME				,F_VALUE
--	)
--	SELECT 
--	S.SETTINGSID	,S.SETTINGSNAME		,S.SETTINGSVALUE
	
--	FROM OASO.dbo.SETTINGS 	S;
--	SET IDENTITY_INSERT T_SETTINGS  OFF;
--END;

BEGIN	-- invoices
	SET IDENTITY_INSERT T_INVOICE ON;
	INSERT INTO T_INVOICE 
	(F_Id			,F_DATE				,F_INVOICENO			,F_CUSTOMERID
	,F_AMOUNT		,F_MANUALINVNO		,F_CANCELED
	,F_CANCELEDDATE	,F_CANCELEDREASON	)
	SELECT 
	C.ID			,C.[DATE]			,C.INVOICENO			,C.CUSTOMERID
	,C.TOTALAMOUNT	,C.MANUALINVOICENO	,C.CANCELED
	,C.CANCELEDDATE	,C.CANCELEDREASON	
	FROM OASO.dbo.INVOICES 	C;
	SET IDENTITY_INSERT T_INVOICE  OFF;
END;
GO

BEGIN	-- PURCHASE VOUCHERS
	SET IDENTITY_INSERT T_PURCHASE_VOUCHERS ON;
	INSERT INTO T_PURCHASE_VOUCHERS 
	(F_Id			,F_VOUCHERDATE		,F_VOUCHERNO			,F_SUPPLIERID
	,F_TOTALAMOUNT	,F_BILLNO			,	F_SHOPNAME)
	SELECT 
	C.RecordId		,C.[VoucherDate]	,C.VoucherNo			,IIF( C.SupplierID=0,6, C.SUPPLIERID)
	,C.TotalAmount	,C.BillNo			,C.supplier
	FROM OASO.dbo.Purchases	C;
	SET IDENTITY_INSERT T_PURCHASE_VOUCHERS OFF;
END;
GO
BEGIN	-- payment voucher
	SET IDENTITY_INSERT [dbo].[T_Payment_Voucher] ON;
	INSERT INTO [dbo].[T_Payment_Voucher]
	(F_Id			,F_VOUCHER_DATE		,F_VOUCHER_NO			,F_PAID_TO_ACC_ID
	,F_AMOUNT							,F_IS_CHEQUE_PAYMENT	
	,[F_PAID_BY_ACC_ID]		
	,[F_CHEQUE_NO]	
	,[F_CHEQUE_DATE]	
	,[F_DESCRIPTION])
	SELECT 
	C.Id			,C.[Date]			,C.VoucherNo			,PAIDTOACCID
	,C.CHQAmount+C.CASHAMOUNT			,IIF(C.CHQAMOUNT>0,1,0)	
	,(SELECT TOP 1 [BankAccID] FROM OASO.DBO.[ISSUEDChqs]  IC WHERE IC.TRANSACTIONTYPE='PMT' AND IC.TRANSACTIONID=C.Id )
	,(SELECT TOP 1 [ChqNo] FROM OASO.DBO.[ISSUEDChqs]  IC WHERE IC.TRANSACTIONTYPE='PMT' AND IC.TRANSACTIONID=C.Id )
	,(SELECT TOP 1 [ChqDate] FROM OASO.DBO.[ISSUEDChqs]  IC WHERE IC.TRANSACTIONTYPE='PMT' AND IC.TRANSACTIONID=C.Id )					
	,C.DESCRIPTION
	FROM OASO.dbo.PAYMENTS	C;
	SET IDENTITY_INSERT [dbo].[T_Payment_Voucher] OFF;
END;
GO

BEGIN	-- ISSUED_CHEQUES
	SET IDENTITY_INSERT [dbo].[T_ISSUED_CHEQUES] ON;
	INSERT INTO [dbo].[T_ISSUED_CHEQUES]
	(F_Id				    ,[F_BANK_ACC_ID]		    ,[F_CHEQUE_NO]
    ,[F_CHEQUE_DATE]		,[F_CHEQUE_AMOUNT]		    
	,[F_STATUS]
    ,[F_CLEARED_DATE]	    ,[F_RETURNED_DATE]		    
	,[F_ACCOUNT_TRAN_ID]
	)
	SELECT 
	C.Id					,C.BankAccID				,C.ChqNo
	,C.ChqDate				,C.ChqAmount				
	,(SELECT E.F_ID FROM T_SM_ENUMS E WHERE E.F_ENUM_GRPID=8 AND E.F_VAL =C.Status COLLATE DATABASE_DEFAULT  )
	,C.ClearedDate			,C.ReturnedDate				
	,(SELECT TOP 1 T.[F_ID] FROM [T_Account_Transactions] T INNER JOIN T_SM_ENUMS E 
			ON E.F_ID=T.F_TRANTYPE 
		WHERE (T.F_TRANID =C.[TRANSACTIONID] )
		AND (E.F_VAL =C.TRANSACTIONTYPE COLLATE DATABASE_DEFAULT   )
		AND E.F_ENUM_GRPID=7 )	
	FROM OASO.dbo.ISSUEDChqs	C;
	SET IDENTITY_INSERT [dbo].[T_ISSUED_CHEQUES] OFF;
END;
GO

BEGIN	-- RECEIPT voucher
	SET IDENTITY_INSERT [dbo].[T_Receipt_Voucher] ON;
	INSERT INTO [dbo].[T_Receipt_Voucher]
	(F_Id					,F_VOUCHER_DATE					,F_VOUCHER_NO			
	,[F_RECEIVED_BY_ACC_ID]	
	,F_AMOUNT				,F_IS_CASH_RECEIPT	
	,[F_RECEIVED_TO_ACC_ID]
	,[F_CHEQUE_NO]	
	,[F_CHEQUE_DATE]	
	,[F_DESCRIPTION])
	SELECT 
	C.Id					,C.[Date]						,C.VoucherNo			
	,(SELECT F_AccountID FROM T_customers TC WHERE TC.F_ID= C.CustomerID )
	,C.[TotalAmount]		,IIF(C.[ChequeAmount]>0,0,1)	
	,IIF(C.[ChequeAmount]>0,153,		
		ISNULL((SELECT TOP 1 TA.F_ACCOUNTID FROM [dbo].[T_Account_Transactions] TA 
			WHERE TA.F_AMOUNT>0 AND TA.F_VOUCHERNO  =C.[VoucherNo] COLLATE DATABASE_DEFAULT),3))
	,(SELECT TOP 1 CC.ChqNo FROM OASO.[dbo].[CustomersChqs] CC WHERE CC.[Collections_recordID]=C.Id )
	,(SELECT TOP 1 CC.[ChqDate] FROM OASO.[dbo].[CustomersChqs] CC WHERE CC.[Collections_recordID]=C.Id )
	,NULL
	FROM OASO.[dbo].[Collections]C  ;
	SET IDENTITY_INSERT [dbo].[T_Receipt_Voucher] OFF;
END;
GO

BEGIN	-- RECEIVED CHEQUES
	SET IDENTITY_INSERT [dbo].[T_RCEIVED_CHEQUES] ON;
	INSERT INTO [dbo].[T_RCEIVED_CHEQUES]
	(F_ID				    ,[F_BANK_ACC_ID]		    ,[F_CHEQUE_NO]
    ,[F_CHEQUE_DATE]		,[F_CHEQUE_AMOUNT]		    
	,[F_STATUS]
    ,[F_CLEARED_DATE]	    ,[F_RETURNED_DATE]		    
	,[F_ACCOUNT_TRAN_ID]
	)
	SELECT 
	C.Id					,C.BankAccountID			,C.ChqNo
	,C.ChqDate				,C.ChqAmount				
	,(SELECT E.F_ID FROM T_SM_ENUMS E WHERE E.F_ENUM_GRPID=8 AND E.F_VAL =C.Status COLLATE DATABASE_DEFAULT  )
	,C.ClearedDate			,C.ReturnedDate				
	,(SELECT TOP 1 T.[F_ID] FROM [T_Account_Transactions] T 
		WHERE T.F_TRANID =C.[Collections_recordID]
		AND T.F_TRANTYPE=1687 AND T.F_AMOUNT>0)	
	FROM OASO.[dbo].[CustomersChqs]   C 
		WHERE 	(SELECT COUNT(*)  FROM [T_Account_Transactions] T 
		WHERE T.F_TRANID =C.[Collections_recordID]
		AND T.F_TRANTYPE=1687 AND T.F_AMOUNT>0)	>0;
	SET IDENTITY_INSERT [dbo].[T_RCEIVED_CHEQUES] OFF;
END;
GO









